name: Semgrep
on:
  pull_request: {}
  push:
    branches:
      - rzp_main
jobs:
  semgrep:
    name: Scan
    runs-on: [self-hosted]
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
